update

diff --git a/chkup b/chkup
--- a/chkup
+++ b/chkup
@@ -1,7 +1,7 @@
 #!/bin/bash
-# $Id: chkup,v 1.82 2015/06/09 10:06:20 fulford Exp fulford $
+# $Id: chkup,v 1.83 2015/06/09 10:35:56 fulford Exp fulford $
 # $Source: /src/merlin/usr/local/etc/RCS/chkup,v $
-# $Revision: 1.82 $
+# $Revision: 1.83 $
 # Author C W Fulford.
 # Copyright 2014 (c) C W Fulford.
 # Licensed for public use under the LGPL, .
@@ -29,16 +29,24 @@ fi
 config=${config:-"/usr/local/etc/chkup.cf"}
 
 if [ ! -f $config ] ;then
-		[ "$verbose" ] && echo "$cmd: $config not found">&2
+		echo "$cmd: $config not found">&2
 fi
 lock=/tmp/$cmd.$clientid.lock
 tcfg=/tmp/$cmd.t$$
 tmp=/var/tmp/$cmd$$
 
+_end () {
+	rm  $tmp 
+	[ -f $tcfg ] && rm $tcfg
+	exit $rval
+}
+
 [ -f $lock ] && {
-	[ "$verbose" ] &&echo "$cmd: failed - $lock already set" >&2
+	echo "$cmd: failed - $lock already set" >&2
 	exit 1
 }
+
+
 
 if [ -f $config ];then
 	if grep -e "^$clientid" $config >/dev/null ;then
@@ -54,6 +62,11 @@ if [ -f $config ];then
 	fi
 fi
 
+getent hosts $host>/dev/null ||{
+	echo "$cmd: can't resolve $host" >&2
+	rval=1
+	_end 
+}
 
 [ -n "$_rcpts" -a -n "$rcpts" ] && $rcpts="$rcpts,$_rcpts"
 rcpts=${rcpts:-`id -nu`}
@@ -66,14 +79,15 @@ _alert () { case $1 in
 	     [ "$log" ] && logger -t "$cmd:" "$host $ports $1"
 	}
 
+
+
 _up () { [ "$ports" ] && opt="-p${ports}"
 	if nmap -Pn $opt $host|
 		tee $tmp|grep filtered >/dev/null 2>&1 ;then
-		rval=1
+		return 1
 	else
-		rval=0
+		return 0
 	fi
-	return $rval
 }
 while ! _up ;do
 	echo "$host port(s) down" >&2
@@ -85,6 +99,7 @@ while ! _up ;do
 	[ $c -gt 10 ] &&{
 		echo "$cmd: $host down for 55 minutes! Giving up"
 		_alert fail
+		rval=1	
 	}
 done
 [ $verbose ] && cat $tmp
@@ -93,9 +108,6 @@ if [ -f $lock ] ;then
 	_alert up
 	rm $lock
 fi
-rm  $tmp 
-[ -f $tcfg ] && rm $tcfg
-exit $rval
 
 ######################################################################
 # This program is free software: you can redistribute it and or      #
